### PR TITLE
Router fixes

### LINKED ISSUE #1455: Sequencer constantly logs "Bid Post Error"
**Describe the bug**
Logs are filled with this error.

**To Reproduce**
See log filter here:

https://app.datadoghq.com/logs?query=-service%3A%28lighthouse%20OR%20router%29%20-container_name%3Atestnet-staging-sequencer&cols=host%2Cservice%2C%40error.context.transferId&index=core-services-testnet&integration_id=&integration_short_name=&messageDisplay=inline&saved_view=1018000&stream_sort=desc&viz=stream&from_ts=1656430364735&to_ts=1656431264735&live=true

**Additional context**
Seeing this log a lot: `MissingXCall: No XCall was found in the subgraph for this auction.` This should never happen so we need to track down why routers are sending a bid which doesn't exist on the sequencer's subgraph.

Fixes: #1679

### LINKED ISSUE #1680: fixes for router
**Describe the bug**

- Fix bid version invalid error at the router
- setup sanity check of supported router bid during setup at the router

Fixes #1679

**To Reproduce**
3. 

**Additional context**

### PR DESCRIPTION
**Pull request by sanchaymittal**
## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## Related Issue(s)

Fixes 

Fixes #1455
Fixes #1680

### CODE REVIEW

File: packages/agents/router/src/subscriber/subscriber.ts [hunk 1]
```diff
@@ -93,10 +98,24 @@ export const makeSubscriber = async (_configOverride?: NxtpRouterConfig) => {
...
+      context.logger.info("supportedBidVersion response received from sequencer", requestContext, methodContext, {
         response: res.data,
       });
+
+      const supportedBidVersion: string = res.data;
+      // check if bid router version is compatible with hosted sequencer
+      const checkVersion = compare(version, supportedBidVersion, "<");
+      if (checkVersion) {
+        context.logger.error(
+          "Invalid Bid Version, please update router! Exiting :(",
```
Comment (rhlsthrm) [inline packages/agents/router/src/subscriber/subscriber.ts:111]: It's not technically bid version, it's sequencer version.

File: packages/agents/sequencer/src/lib/errors/bid.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ export class ParamsInvalid extends NxtpError {
```
Comment (rhlsthrm) [inline packages/agents/sequencer/src/lib/errors/bid.ts:8]: RouterVersionInvalid?

File: packages/agents/router/src/errors/execute.ts [hunk 3]
```diff
@@ -23,6 +23,11 @@ export class MissingXCall extends ExecuteError {
     super("Transfer is missing XCall information", context, MissingXCall.name);
   }
 }
+export class BidVersionInvalid extends NxtpError {
```
Comment (rhlsthrm) [inline packages/agents/router/src/errors/execute.ts:26]: RouterVersionInvalid?

**Review by rhlsthrm — APPROVED** [review]

File: packages/agents/router/src/subscriber/subscriber.ts (hunk 1 above)
Comment (sanchaymittal) [reply packages/agents/router/src/subscriber/subscriber.ts:111]: it's supportedBidVersion, In the sequencer config, we set the supported version so that the router version needs to be >= supportedBidVersion.
